### PR TITLE
New  "pathbytes" PropID

### PR DESCRIPTION
**Pull request by ethteck**
This new PropID allows the user to get the file path in raw bytes rather than in a string format. The bytes can be decoded with the proper encoding, as sometimes filenames are encoded in zips correctly and information is lost when converting the mojibake to a Java String.

### CODE REVIEW

**Comment by ethteck** [comment]
Hi @borisbrodski, sorry for the (extremely) late response here. I'm actually slated to work on this next week to hopefully get my branch into a mergeable state to your upstream repo.

I'll try to prepare some tests at the beginning of next week. Looking forward to working with you to get this into the main fork!

**Comment by borisbrodski** [comment]
Hi @ethteck , lets do it :)

**Comment by ethteck** [comment]
:) happy to hear that! I've added a unit test - let me know what you think. It confirms that we can get the raw bytes from the path of some Japanese files in a zip and decode them to the correct UTF-8 string, where the plain Path prop doesn't work since the original string gets mangled when it goes from C++ to Java.

**Comment by borisbrodski** [comment]
Sorry, just realized, that this is not my repository :)

Could you please create a pull request for the master of the "borisbrodski/sevenzipjbinding"?

PS
The unit-test is looking good! Thank you :+1:

**Comment by ethteck** [comment]
Oops, yes! I created https://github.com/borisbrodski/sevenzipjbinding/pull/36 :)

**Pull request merged**
